name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@{version}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
          DISABLE_EVENTS: "COMMENTS"
          COMMIT_MSG: "Update README with latest Activities"
          TIMEZONE_OFFSET: "+2:00"
          DATE_STRING: "Last update: `{DATE}`"
          DATE_FORMAT: "dd.mm.yyyy HH:MM:ss"